import { ERROR_CODES, ERROR_KINDS, HTTP_STATUS_BY_KIND, retryOf, type ErrorCode, type ErrorKind } from '@openfleet/shared';

export const GENERATOR_PATH = 'scripts/errors/generateErrorReference.ts';
export const REGENERATE_COMMAND = 'pnpm docs:errors';

const HEADER = `<!-- Generated by ${GENERATOR_PATH}: do not edit. Regenerate with \`${REGENERATE_COMMAND}\`. -->`;

const INTRO = `# Error codes

Generated by \`${GENERATOR_PATH}\`: do not edit. Run \`${REGENERATE_COMMAND}\` after changing \`ERROR_CODES\` in \`packages/shared/src/errors.ts\`;
a test fails while this file is out of date.

**What is generated.** Every code of the registry with its kind, HTTP status and retry rule, read from \`@openfleet/shared\`.
**What is not.** The default message and hint of each code, the typed class that raises it and the desktop copy are not generated:
they live in closures of \`describeError\` (core) and in the Angular app, and cannot be read without running them.
The registry carries no per-code description either, so the tables have no "meaning" column.
`;

const ENVELOPE = `## The envelope

REST, MCP and WebSocket report one error shape: \`{ error: <code>, kind, retry, message, hint?, detail?, id? }\`.
\`error\` is the stable identity of an error: key on it, never on the message. \`id\` (8 hex characters) exists only for kind \`internal\`
and is the reference in the daemon log.

Retry rules: \`never\` means fix the input; \`after_refresh\` means reload what moved, then decide; \`later\` means send the same call again.
`;

const MCP_GRAMMAR = `## MCP refusals (the agents' grammar)

A refusal of an MCP tool is one line:

\`\`\`
error <code>: <message> (retry: never|after_refresh|later[, ref <id>])
\`\`\`

Read the code after \`error\`, and the retry rule and the ref only from the \`(retry: …, ref …)\` tag at the end of the line, never from the message text.

Two refusals sit outside this grammar:

- A tool argument that fails the SDK's schema validation is answered by the MCP SDK as a JSON-RPC error with code \`-32602\`, not as an \`error <code>:\` line.
- A missing or wrong MCP token is answered with HTTP 401 on \`/mcp\`, as the REST envelope (\`error: unauthorized\`), before any tool runs.
`;

const codesOfKind = (kind: ErrorKind): ErrorCode[] =>
  (Object.keys(ERROR_CODES) as ErrorCode[]).filter((code) => ERROR_CODES[code].kind === kind);

const kindsTable = (): string => {
  const rows = ERROR_KINDS.map((kind) => `| \`${kind}\` | ${HTTP_STATUS_BY_KIND[kind]} | ${codesOfKind(kind).length} |`);
  return ['| Kind | HTTP status | Codes |', '| --- | --- | --- |', ...rows].join('\n');
};

const codesTable = (kind: ErrorKind): string => {
  const rows = codesOfKind(kind).map((code) => `| \`${code}\` | ${HTTP_STATUS_BY_KIND[kind]} | \`${retryOf(code)}\` |`);
  return [`### ${kind}`, '', '| Code | HTTP status | Retry |', '| --- | --- | --- |', ...rows].join('\n');
};

/** Renders docs/errors.md from the registry alone: the same registry always gives the same text. */
export function renderErrorReference(): string {
  const kindSections = ERROR_KINDS.map(codesTable).join('\n\n');
  const sections = [HEADER, INTRO, ENVELOPE, '## Kinds\n\n' + kindsTable(), '## Codes\n\n' + kindSections, MCP_GRAMMAR];
  return `${sections.join('\n\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
